[rospy.client][INFO] 2020-09-01 10:18:21,815: init_node, name[/diagnostic_rplidar_head_topic], pid[16891]
[xmlrpc][INFO] 2020-09-01 10:18:21,815: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-01 10:18:21,815: Started XML-RPC server [http://cuboid:43597/]
[rospy.init][INFO] 2020-09-01 10:18:21,815: ROS Slave URI: [http://cuboid:43597/]
[rospy.impl.masterslave][INFO] 2020-09-01 10:18:21,815: _ready: http://cuboid:43597/
[xmlrpc][INFO] 2020-09-01 10:18:21,816: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-09-01 10:18:21,816: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-09-01 10:18:21,916: registered with master
[rospy.rosout][INFO] 2020-09-01 10:18:21,916: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-01 10:18:21,918: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-01 10:18:21,919: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-01 10:18:21,931: topic[/head_scan] adding connection to [http://cuboid:44831/], count 0
[rospy.internal][INFO] 2020-09-01 10:18:22,077: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-01 10:18:22,177: topic[/diagnostics] adding connection to [/diag_agg], count 0
[rospy.internal][INFO] 2020-09-01 10:25:42,071: topic[/diagnostics] removing connection to /diag_agg
[rospy.impl.masterslave][INFO] 2020-09-01 10:25:43,234: external shutdown request from [/rosnode]: user request
[rospy.core][INFO] 2020-09-01 10:25:43,234: signal_shutdown [external shutdown request from [/rosnode]: [user request]]
[rospy.internal][INFO] 2020-09-01 10:25:43,237: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-01 10:25:43,238: topic[/head_scan] removing connection to http://cuboid:44831/
[rospy.internal][WARNING] 2020-09-01 10:25:43,238: Unknown error initiating TCP/IP socket to cuboid:36275 (http://cuboid:44831/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-09-01 10:25:43,238: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.core][INFO] 2020-09-01 10:25:43,339: signal_shutdown [atexit]
