[rospy.client][INFO] 2020-09-01 10:18:15,989: init_node, name[/diagnostic_imu_topic], pid[15683]
[xmlrpc][INFO] 2020-09-01 10:18:15,989: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-01 10:18:15,989: Started XML-RPC server [http://cuboid:45827/]
[rospy.init][INFO] 2020-09-01 10:18:15,989: ROS Slave URI: [http://cuboid:45827/]
[rospy.impl.masterslave][INFO] 2020-09-01 10:18:15,989: _ready: http://cuboid:45827/
[rospy.registration][INFO] 2020-09-01 10:18:15,990: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-09-01 10:18:15,990: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-01 10:18:16,090: registered with master
[rospy.rosout][INFO] 2020-09-01 10:18:16,090: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-01 10:18:16,092: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-01 10:18:16,093: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-01 10:18:16,105: topic[/gyro/imu] adding connection to [http://cuboid:37895/], count 0
[rospy.internal][INFO] 2020-09-01 10:18:16,357: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-01 10:18:16,357: topic[/diagnostics] adding connection to [/diag_agg], count 0
[rospy.internal][INFO] 2020-09-01 10:25:41,740: topic[/diagnostics] removing connection to /diag_agg
[rospy.impl.masterslave][INFO] 2020-09-01 10:25:41,914: external shutdown request from [/rosnode]: user request
[rospy.core][INFO] 2020-09-01 10:25:41,914: signal_shutdown [external shutdown request from [/rosnode]: [user request]]
[rospy.internal][INFO] 2020-09-01 10:25:41,917: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-01 10:25:41,918: topic[/gyro/imu] removing connection to http://cuboid:37895/
[rospy.internal][WARNING] 2020-09-01 10:25:41,919: Unknown error initiating TCP/IP socket to cuboid:38659 (http://cuboid:37895/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-09-01 10:25:41,919: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.core][INFO] 2020-09-01 10:25:42,083: signal_shutdown [atexit]
