[rospy.client][INFO] 2020-09-10 10:21:53,069: init_node, name[/diagnostic_map_scan_rear], pid[17279]
[xmlrpc][INFO] 2020-09-10 10:21:53,070: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-10 10:21:53,070: Started XML-RPC server [http://cuboid0009:35817/]
[rospy.init][INFO] 2020-09-10 10:21:53,070: ROS Slave URI: [http://cuboid0009:35817/]
[rospy.impl.masterslave][INFO] 2020-09-10 10:21:53,070: _ready: http://cuboid0009:35817/
[rospy.registration][INFO] 2020-09-10 10:21:53,071: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-09-10 10:21:53,071: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-10 10:21:53,170: registered with master
[rospy.rosout][INFO] 2020-09-10 10:21:53,171: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-10 10:21:53,172: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-10 10:21:53,173: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-10 10:21:53,185: topic[/map_scan_rear] adding connection to [http://cuboid0009:41965/], count 0
[rospy.internal][INFO] 2020-09-10 10:21:53,363: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-10 10:21:53,464: topic[/diagnostics] adding connection to [/diag_agg], count 0
[rospy.internal][INFO] 2020-09-10 10:23:24,711: topic[/diagnostics] removing connection to /diag_agg
[rospy.impl.masterslave][INFO] 2020-09-10 10:23:24,918: external shutdown request from [/rosnode]: user request
[rospy.core][INFO] 2020-09-10 10:23:24,918: signal_shutdown [external shutdown request from [/rosnode]: [user request]]
[rospy.internal][INFO] 2020-09-10 10:23:24,921: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-10 10:23:24,921: topic[/map_scan_rear] removing connection to http://cuboid0009:41965/
[rospy.internal][WARNING] 2020-09-10 10:23:24,921: Unknown error initiating TCP/IP socket to cuboid0009:60941 (http://cuboid0009:41965/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-09-10 10:23:24,922: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.core][INFO] 2020-09-10 10:23:25,257: signal_shutdown [atexit]
